<a href="https://colab.research.google.com/github/jocode/machine-learning-python/blob/master/Introducci%C3%B3n_a_python_cient%C3%ADfico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Crear Arrays




In [0]:
# Importar la librería
import numpy as np

In [5]:
a1 = np.array([1,2,3,4])    # Con una lista
type(a1)

numpy.ndarray

In [7]:
a2 = np.arange(10)     # np.arange es un método similar a list
a2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a3 = np.zeros((2,3))  # crear una listta de 2 dimensiones, pre-rellenada con zeros
a4 = np.ones((2,3))   # Crear una lista de dos dimensiones, pre-rellenada con unos

In [9]:
from IPython.display import display
display(a3); display(a4);

array([[0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.]])


`np.linspace(a,b,n)` es una función que permite crear arrays de una dimensión, de largo n, y que contienen puntos entre a y b, distanciados de forma regular. La distancia entre cada punto sera de $(b-a)/(n-1)$.


In [10]:
a5 = np.linspace(0,1,10)
display(a5)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
# Dtypes
a5.dtype

dtype('float64')